package de.cau.cs.kieler.kex.controller;

public enum ExampleElement {

	ID, NAME, DESCRIPTION, VERSION, DEST_LOCATION, CONTACT, SOURCETYPE, RESOURCES, CATEGORIES, HEAD_RESOURCE, CREATE_CATEGORIES, DELETE_CATEGORIES;

}
