package de.cau.cs.kieler.kex.controller;

public enum ExampleElement {

	DESCRIPTION, VERSION, DEST_LOCATION, CONTACT, SOURCETYPE, RESOURCES, CATEGORIES, CREATE_CATEGORIES, CREATE_EXAMPLE_FOLDER, OVERVIEW_PIC, TITLE, AUTHOR;

}
