/*
 * generated by Xtext
 */
package de.cau.cs.kieler.ksbase;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FeatureDefinitionRuntimeModule extends de.cau.cs.kieler.ksbase.AbstractFeatureDefinitionRuntimeModule {

}
