/*
 * generated by Xtext
 */
package de.cau.cs.kieler.uml.sequence.text;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension
 * registry.
 */
public class SequenceRuntimeModule extends
        de.cau.cs.kieler.uml.sequence.text.AbstractSequenceRuntimeModule {

    /**
     * {@inheritDoc}
     */
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return SequenceValueConverter.class;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
        return NullGlobalScopeProvider.class;
    }

}
