/*
 * generated by Xtext 2.12.0
 */
package de.cau.cs.kieler.grana.text.ide

import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider
import de.cau.cs.kieler.grana.text.ide.contentassist.GranaIdeProposalProvider

/**
 * Use this class to register ide components.
 */
class GranaIdeModule extends AbstractGranaIdeModule {
    
     def Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
        GranaIdeProposalProvider
    }
    
}
