/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.ogdf.lib;

public class DScaler {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DScaler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DScaler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OgdfJNI.delete_DScaler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DScaler(DRect from, DRect to) {
    this(OgdfJNI.new_DScaler(DRect.getCPtr(from), from, DRect.getCPtr(to), to), true);
  }

  public DRect from() {
    return new DRect(OgdfJNI.DScaler_from(swigCPtr, this), false);
  }

  public DRect to() {
    return new DRect(OgdfJNI.DScaler_to(swigCPtr, this), false);
  }

  public double scaleToX(double x) {
    return OgdfJNI.DScaler_scaleToX(swigCPtr, this, x);
  }

  public double scaleToY(double y) {
    return OgdfJNI.DScaler_scaleToY(swigCPtr, this, y);
  }

  public double scaleWidth(double width) {
    return OgdfJNI.DScaler_scaleWidth(swigCPtr, this, width);
  }

  public double scaleHeight(double height) {
    return OgdfJNI.DScaler_scaleHeight(swigCPtr, this, height);
  }

}
