/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package net.ogdf.lib;

public class PlanarizationLayout extends UMLLayoutModule {
  private long swigCPtr;

  protected PlanarizationLayout(long cPtr, boolean cMemoryOwn) {
    super(OgdfJNI.SWIGPlanarizationLayoutUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PlanarizationLayout obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      OgdfJNI.delete_PlanarizationLayout(swigCPtr);
    }
    swigCPtr = 0;
    super.delete();
  }

  public PlanarizationLayout() {
    this(OgdfJNI.new_PlanarizationLayout(), true);
  }

  public void call(GraphAttributes arg0) {
    OgdfJNI.PlanarizationLayout_call__SWIG_0(swigCPtr, this, GraphAttributes.getCPtr(arg0), arg0);
  }

  public void call(UMLGraph arg0) {
    OgdfJNI.PlanarizationLayout_call__SWIG_1(swigCPtr, this, UMLGraph.getCPtr(arg0), arg0);
  }

}
