/*
 * generated by Xtext
 */
package de.cau.cs.kieler.kiml.graphviz.dot;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GraphvizDotRuntimeModule extends de.cau.cs.kieler.kiml.graphviz.dot.AbstractGraphvizDotRuntimeModule {

}
