<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="actors"
    nsURI="http://actors/1.0" nsPrefix="actors">
  <eAnnotations source=""/>
  <eAnnotations source="Doc" references="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&#xA;erhrthrt"/>
    </eAnnotations>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="NamedObject" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="childEntities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" eType="#//Link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childLinks" upperBound="-1"
        eType="#//Link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childRelations" upperBound="-1"
        eType="#//Relation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//Linkable #//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//Link"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" eSuperTypes="#//Linkable #//NamedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedPorts" lowerBound="1"
        upperBound="-1" eType="#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Linkable" eOpposite="#//Linkable/outgoingLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Linkable" eOpposite="#//Linkable/incomingLinks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedEntities" lowerBound="2"
        upperBound="2" eType="#//Linkable" eOpposite="#//Linkable/links"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Linkable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingLinks" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" eOpposite="#//Link/linkedEntities">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//Entity #//Linkable"/>
</ecore:EPackage>
