grammar de.cau.cs.kieler.kiml.config.text.LayoutConfig 
    with org.eclipse.elk.graph.text.ElkGraph

import "http://www.eclipse.org/emf/2002/Ecore" as ecore
import "http://www.eclipse.org/elk/ElkGraph"

RootNode returns ElkNode:
    {ElkNode}
    (children+=ElkNode)+;

ElkNode returns ElkNode:
    identifier=ID '{'
        properties+=Property* 
        ('ref' children+=RefElkNode)*    
    '}';

RefElkNode returns ElkNode:
    identifier=ID '{'
        properties+=Property*
    '}'
;