/*
* generated by Xtext
*/
package de.cau.cs.kieler.uml.sequence.text.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import de.cau.cs.kieler.uml.sequence.text.services.SequenceGrammarAccess;

public class SequenceParser extends AbstractContentAssistParser {
	
	@Inject
	private SequenceGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected de.cau.cs.kieler.uml.sequence.text.ui.contentassist.antlr.internal.InternalSequenceParser createParser() {
		de.cau.cs.kieler.uml.sequence.text.ui.contentassist.antlr.internal.InternalSequenceParser result = new de.cau.cs.kieler.uml.sequence.text.ui.contentassist.antlr.internal.InternalSequenceParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getInteractionAccess().getAlternatives(), "rule__Interaction__Alternatives");
					put(grammarAccess.getTwoLifelineMessageAccess().getAlternatives_5(), "rule__TwoLifelineMessage__Alternatives_5");
					put(grammarAccess.getTwoLifelineMessageAccess().getAlternatives_6(), "rule__TwoLifelineMessage__Alternatives_6");
					put(grammarAccess.getOneLifelineMessageAccess().getAlternatives_2(), "rule__OneLifelineMessage__Alternatives_2");
					put(grammarAccess.getOneLifelineMessageAccess().getAlternatives_4(), "rule__OneLifelineMessage__Alternatives_4");
					put(grammarAccess.getMessageTypeAccess().getAlternatives(), "rule__MessageType__Alternatives");
					put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
					put(grammarAccess.getSequenceDiagramAccess().getGroup(), "rule__SequenceDiagram__Group__0");
					put(grammarAccess.getSequenceDiagramAccess().getGroup_3(), "rule__SequenceDiagram__Group_3__0");
					put(grammarAccess.getLocalVariableAccess().getGroup(), "rule__LocalVariable__Group__0");
					put(grammarAccess.getLifelineAccess().getGroup(), "rule__Lifeline__Group__0");
					put(grammarAccess.getTwoLifelineMessageAccess().getGroup(), "rule__TwoLifelineMessage__Group__0");
					put(grammarAccess.getTwoLifelineMessageAccess().getGroup_5_1(), "rule__TwoLifelineMessage__Group_5_1__0");
					put(grammarAccess.getTwoLifelineMessageAccess().getGroup_6_1(), "rule__TwoLifelineMessage__Group_6_1__0");
					put(grammarAccess.getTwoLifelineMessageAccess().getGroup_7(), "rule__TwoLifelineMessage__Group_7__0");
					put(grammarAccess.getTwoLifelineMessageAccess().getGroup_8(), "rule__TwoLifelineMessage__Group_8__0");
					put(grammarAccess.getOneLifelineMessageAccess().getGroup(), "rule__OneLifelineMessage__Group__0");
					put(grammarAccess.getOneLifelineMessageAccess().getGroup_4_1(), "rule__OneLifelineMessage__Group_4_1__0");
					put(grammarAccess.getOneLifelineMessageAccess().getGroup_5(), "rule__OneLifelineMessage__Group_5__0");
					put(grammarAccess.getOneLifelineEndBlockAccess().getGroup(), "rule__OneLifelineEndBlock__Group__0");
					put(grammarAccess.getOneLifelineNoteAccess().getGroup(), "rule__OneLifelineNote__Group__0");
					put(grammarAccess.getDestroyLifelineEventAccess().getGroup(), "rule__DestroyLifelineEvent__Group__0");
					put(grammarAccess.getFragmentAccess().getGroup(), "rule__Fragment__Group__0");
					put(grammarAccess.getSectionAccess().getGroup(), "rule__Section__Group__0");
					put(grammarAccess.getSectionAccess().getGroup_1(), "rule__Section__Group_1__0");
					put(grammarAccess.getRefinementAccess().getGroup(), "rule__Refinement__Group__0");
					put(grammarAccess.getRefinementAccess().getGroup_5(), "rule__Refinement__Group_5__0");
					put(grammarAccess.getSequenceDiagramAccess().getDiagramNameAssignment_2(), "rule__SequenceDiagram__DiagramNameAssignment_2");
					put(grammarAccess.getSequenceDiagramAccess().getLocalsAssignment_3_1(), "rule__SequenceDiagram__LocalsAssignment_3_1");
					put(grammarAccess.getSequenceDiagramAccess().getLocalsAssignment_3_2(), "rule__SequenceDiagram__LocalsAssignment_3_2");
					put(grammarAccess.getSequenceDiagramAccess().getLifelinesAssignment_4(), "rule__SequenceDiagram__LifelinesAssignment_4");
					put(grammarAccess.getSequenceDiagramAccess().getInteractionsAssignment_5(), "rule__SequenceDiagram__InteractionsAssignment_5");
					put(grammarAccess.getLocalVariableAccess().getTypeAssignment_0(), "rule__LocalVariable__TypeAssignment_0");
					put(grammarAccess.getLocalVariableAccess().getNameAssignment_1(), "rule__LocalVariable__NameAssignment_1");
					put(grammarAccess.getLifelineAccess().getCaptionAssignment_1(), "rule__Lifeline__CaptionAssignment_1");
					put(grammarAccess.getLifelineAccess().getNameAssignment_3(), "rule__Lifeline__NameAssignment_3");
					put(grammarAccess.getTwoLifelineMessageAccess().getSourceLifelineAssignment_0(), "rule__TwoLifelineMessage__SourceLifelineAssignment_0");
					put(grammarAccess.getTwoLifelineMessageAccess().getMessageTypeAssignment_1(), "rule__TwoLifelineMessage__MessageTypeAssignment_1");
					put(grammarAccess.getTwoLifelineMessageAccess().getMessageAssignment_2(), "rule__TwoLifelineMessage__MessageAssignment_2");
					put(grammarAccess.getTwoLifelineMessageAccess().getTargetLifelineAssignment_4(), "rule__TwoLifelineMessage__TargetLifelineAssignment_4");
					put(grammarAccess.getTwoLifelineMessageAccess().getSourceStartBlockAssignment_5_0(), "rule__TwoLifelineMessage__SourceStartBlockAssignment_5_0");
					put(grammarAccess.getTwoLifelineMessageAccess().getSourceEndBlockAssignment_5_1_0(), "rule__TwoLifelineMessage__SourceEndBlockAssignment_5_1_0");
					put(grammarAccess.getTwoLifelineMessageAccess().getSourceEndBlockCountAssignment_5_1_1(), "rule__TwoLifelineMessage__SourceEndBlockCountAssignment_5_1_1");
					put(grammarAccess.getTwoLifelineMessageAccess().getTargetStartBlockAssignment_6_0(), "rule__TwoLifelineMessage__TargetStartBlockAssignment_6_0");
					put(grammarAccess.getTwoLifelineMessageAccess().getTargetEndBlockAssignment_6_1_0(), "rule__TwoLifelineMessage__TargetEndBlockAssignment_6_1_0");
					put(grammarAccess.getTwoLifelineMessageAccess().getTargetEndBlockCountAssignment_6_1_1(), "rule__TwoLifelineMessage__TargetEndBlockCountAssignment_6_1_1");
					put(grammarAccess.getTwoLifelineMessageAccess().getSourceNoteAssignment_7_1(), "rule__TwoLifelineMessage__SourceNoteAssignment_7_1");
					put(grammarAccess.getTwoLifelineMessageAccess().getTargetNoteAssignment_8_1(), "rule__TwoLifelineMessage__TargetNoteAssignment_8_1");
					put(grammarAccess.getOneLifelineMessageAccess().getLifelineAssignment_0(), "rule__OneLifelineMessage__LifelineAssignment_0");
					put(grammarAccess.getOneLifelineMessageAccess().getMessageTypeAssignment_1(), "rule__OneLifelineMessage__MessageTypeAssignment_1");
					put(grammarAccess.getOneLifelineMessageAccess().getCaptionAssignment_3(), "rule__OneLifelineMessage__CaptionAssignment_3");
					put(grammarAccess.getOneLifelineMessageAccess().getStartBlockAssignment_4_0(), "rule__OneLifelineMessage__StartBlockAssignment_4_0");
					put(grammarAccess.getOneLifelineMessageAccess().getEndBlockAssignment_4_1_0(), "rule__OneLifelineMessage__EndBlockAssignment_4_1_0");
					put(grammarAccess.getOneLifelineMessageAccess().getEndBlockCountAssignment_4_1_1(), "rule__OneLifelineMessage__EndBlockCountAssignment_4_1_1");
					put(grammarAccess.getOneLifelineMessageAccess().getNoteAssignment_5_1(), "rule__OneLifelineMessage__NoteAssignment_5_1");
					put(grammarAccess.getOneLifelineEndBlockAccess().getLifelineAssignment_0(), "rule__OneLifelineEndBlock__LifelineAssignment_0");
					put(grammarAccess.getOneLifelineEndBlockAccess().getEndBlockCountAssignment_2(), "rule__OneLifelineEndBlock__EndBlockCountAssignment_2");
					put(grammarAccess.getOneLifelineNoteAccess().getLifelineAssignment_0(), "rule__OneLifelineNote__LifelineAssignment_0");
					put(grammarAccess.getOneLifelineNoteAccess().getNoteAssignment_2(), "rule__OneLifelineNote__NoteAssignment_2");
					put(grammarAccess.getDestroyLifelineEventAccess().getLifelineAssignment_0(), "rule__DestroyLifelineEvent__LifelineAssignment_0");
					put(grammarAccess.getFragmentAccess().getNameAssignment_1(), "rule__Fragment__NameAssignment_1");
					put(grammarAccess.getFragmentAccess().getSectionsAssignment_2(), "rule__Fragment__SectionsAssignment_2");
					put(grammarAccess.getFragmentAccess().getSectionsAssignment_3(), "rule__Fragment__SectionsAssignment_3");
					put(grammarAccess.getSectionAccess().getLabelAssignment_1_1(), "rule__Section__LabelAssignment_1_1");
					put(grammarAccess.getSectionAccess().getInteractionsAssignment_2(), "rule__Section__InteractionsAssignment_2");
					put(grammarAccess.getSectionAccess().getInteractionsAssignment_3(), "rule__Section__InteractionsAssignment_3");
					put(grammarAccess.getRefinementAccess().getLabelAssignment_2(), "rule__Refinement__LabelAssignment_2");
					put(grammarAccess.getRefinementAccess().getLifelinesAssignment_4(), "rule__Refinement__LifelinesAssignment_4");
					put(grammarAccess.getRefinementAccess().getLifelinesAssignment_5_1(), "rule__Refinement__LifelinesAssignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			de.cau.cs.kieler.uml.sequence.text.ui.contentassist.antlr.internal.InternalSequenceParser typedParser = (de.cau.cs.kieler.uml.sequence.text.ui.contentassist.antlr.internal.InternalSequenceParser) parser;
			typedParser.entryRuleSequenceDiagram();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SequenceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SequenceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
