/*
 * generated by Xtext
 */
package de.cau.cs.kieler.kaom.text;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KaomRuntimeModule extends de.cau.cs.kieler.kaom.text.AbstractKaomRuntimeModule {
    
    public Class<? extends org.eclipse.xtext.linking.ILinker> bindILinker() {
        return KaomLinker.class;
    }
    
    public Class<? extends org.eclipse.xtext.parsetree.reconstr.ITransientValueService> bindITransientValueService() {
        return KaomTransientValueService.class;
    }

}
