/*
 * KIELER - Kiel Integrated Environment for Layout Eclipse RichClient
 *
 * http://www.informatik.uni-kiel.de/rtsys/kieler/
 * 
 * Copyright 2012 by
 * + Christian-Albrechts-University of Kiel
 *   + Department of Computer Science
 *     + Real-Time and Embedded Systems Group
 * 
 * This code is provided under the terms of the Eclipse Public License (EPL).
 * See the file epl-v10.html for the license text.
 */
package de.cau.cs.kieler.papyrus.sequence.graph;

import java.util.LinkedList;
import java.util.List;

import de.cau.cs.kieler.core.math.KVector;

/**
 * Comment representation for SGraphs.
 * 
 * @author grh
 * @kieler.design 2012-11-20 cds, msp
 * @kieler.rating yellow 2012-12-11 cds, ima
 */
public final class SComment extends SGraphElement {
    /**
     * The serialVersionUID is needed for all elements that extends the MapPropertyHolder. It is
     * generated by Eclipse.
     */
    private static final long serialVersionUID = 2543686433908319587L;
    /**
     * The list of elements that the comment is attached to. A comment may have connections to
     * several different objects.
     */
    private List<SGraphElement> attachedTo;
    /**
     * If the comment is attached to an element in the diagram, it will be drawn near to a message
     * and a lifeline.
     */
    private SMessage message;
    /**
     * If the comment is attached to an element in the diagram, it will be drawn near to a message
     * and a lifeline.
     */
    private SLifeline lifeline;
    /** The size of the comment. */
    private KVector size;
    /** The position of the comment. */
    private KVector position;

    /**
     * Constructs a new SComment.
     */
    public SComment() {
        attachedTo = new LinkedList<SGraphElement>();
        size = new KVector();
        position = new KVector();
    }

    /**
     * Get the size of the comment.
     * 
     * @return the KVector with the size
     */
    public KVector getSize() {
        return size;
    }

    /**
     * Get the position of the comment.
     * 
     * @return the KVector with the position
     */
    public KVector getPosition() {
        return position;
    }

    /**
     * Get the SGraphElement to which the comment is attached to.
     * 
     * @return the connected element
     */
    public List<SGraphElement> getAttachedTo() {
        return attachedTo;
    }

    /**
     * Get the message near to which the comment will be drawn if existing.
     * 
     * @return the SMessage near to the comment or null if not existing
     */
    public SMessage getMessage() {
        return message;
    }

    /**
     * Set the message near to which the comment will be drawn.
     * 
     * @param message
     *            the new message
     */
    public void setMessage(final SMessage message) {
        // Delete comment from the old message's comments list
        if (this.message != null) {
            List<SComment> oldComments = this.message.getComments();
            if (oldComments != null) {
                oldComments.remove(this);
            }
        }

        this.message = message;

        // Add comment to the new message's comments list
        if (message != null) {
            List<SComment> comments = message.getComments();
            if (comments != null) {
                if (!comments.contains(this)) {
                    comments.add(this);
                }
            } else {
                comments = new LinkedList<SComment>();
                comments.add(this);
            }
        }
    }

    /**
     * Get the lifeline near to which the comment will be drawn if existing.
     * 
     * @return the SLifeline near to the comment or null if not existing
     */
    public SLifeline getLifeline() {
        return lifeline;
    }

    /**
     * Set the lifeline near to which the comment will be drawn.
     * 
     * @param lifeline
     *            the new lifeline
     */
    public void setLifeline(final SLifeline lifeline) {
        // Delete comment from the old lifeline's comments list
        if (this.lifeline != null) {
            List<SComment> oldComments = this.lifeline.getComments();
            if (oldComments != null) {
                oldComments.remove(this);
            }
        }

        this.lifeline = lifeline;

        // Add comment to the new lifeline's comments list
        if (lifeline != null) {
            List<SComment> comments = lifeline.getComments();
            if (comments != null) {
                if (!comments.contains(this)) {
                    comments.add(this);
                }
            } else {
                comments = new LinkedList<SComment>();
                comments.add(this);
            }
        }
    }
}
