<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="grana" nsURI="http://www.cau.de/cs/kieler/kiml/grana/text/Grana"
    nsPrefix="grana">
  <eClassifiers xsi:type="ecore:EClass" name="Grana">
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalResources" upperBound="-1"
        eType="#//GlobalResourceRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gloobalOutputs" upperBound="-1"
        eType="#//GlobalOutputRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executeAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="execute" unique="false"
        upperBound="-1" eType="#//Job"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobs" upperBound="-1" eType="#//Job"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Job">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutOptions" upperBound="-1"
        eType="ecore:EClass platform:/resource/de.cau.cs.kieler.kiml/model/klayoutdata.ecore#//KIdentifier"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analyses" upperBound="-1"
        eType="#//Analysis" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" eType="#//Output"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegularJob" eSuperTypes="#//Job">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutBeforeAnalysis" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measureExecutionTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeJob" eSuperTypes="#//Job">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rangeOption" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rangeValues" eType="#//Range"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rangeAnalysis" eType="#//Analysis"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rangeAnalysisComponent"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Range"/>
  <eClassifiers xsi:type="ecore:EClass" name="FloatRange" eSuperTypes="#//Range">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntRange" eSuperTypes="#//Range"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntRangeValues" eSuperTypes="#//IntRange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntRangeRange" eSuperTypes="#//IntRange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceReference" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceRefs" unique="false"
        upperBound="-1" eType="#//GlobalResourceRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalResourceRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//LocalResource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output"/>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalOutputRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" eType="#//LocalOutput"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputReference" eSuperTypes="#//Output">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputRef" eType="#//GlobalOutputRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalOutput" eSuperTypes="#//Output">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Analysis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
