/*
 * generated by Xtext
 */
package de.cau.cs.kieler.grana.text.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.cau.cs.kieler.grana.text.ui.internal.GranaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GranaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GranaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GranaActivator.getInstance().getInjector(GranaActivator.DE_CAU_CS_KIELER_GRANA_TEXT_GRANA);
	}
	
}
