/*
* generated by Xtext
*/
package de.cau.cs.kieler.klighd.kdiagram.ui.contentassist;

import de.cau.cs.kieler.klighd.kdiagram.ui.contentassist.AbstractKDiagramProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class KDiagramProposalProvider extends AbstractKDiagramProposalProvider {

}
